[build-system]
requires = ["setuptools>=64.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mazegen"
version = "1.0.0"
description = "Package for creating, rendering and animating a maze"
authors = [
    { name = "adrianag", email = "adrianag@student.42malaga.com" },
    { name = "apalese-", email = "apalese-@student.42malaga.com" }
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["mazegen*"]

[dependency-groups]
dev = [
    "flake8",
    "mypy",
]
